[package]
name = "ca_cert_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rcgen = "0.11"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.24"
rustls = "0.21"
rustls-pemfile = "1.0"
hyper = { version = "0.14", features = ["full"] }
time = "0.3"